/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[..catchAll]': RouteRecordInfo<
      '/[..catchAll]',
      '/:atchAll(.*)',
      { atchAll: ParamValue<true> },
      { atchAll: ParamValue<false> },
      | never
    >,
    '/admin/inquiries/': RouteRecordInfo<
      '/admin/inquiries/',
      '/admin/inquiries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/inquiries/[id]': RouteRecordInfo<
      '/admin/inquiries/[id]',
      '/admin/inquiries/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/jodalsa/': RouteRecordInfo<
      '/jodalsa/',
      '/jodalsa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jodalsa/[id]': RouteRecordInfo<
      '/jodalsa/[id]',
      '/jodalsa/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manual': RouteRecordInfo<
      '/manual',
      '/manual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/materials/': RouteRecordInfo<
      '/materials/',
      '/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/purchase/': RouteRecordInfo<
      '/purchase/',
      '/purchase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/results/': RouteRecordInfo<
      '/results/',
      '/results',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/results/[id]': RouteRecordInfo<
      '/results/[id]',
      '/results/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/tests/': RouteRecordInfo<
      '/tests/',
      '/tests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[username]': RouteRecordInfo<
      '/users/[username]',
      '/users/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[..catchAll].vue': {
      routes:
        | '/[..catchAll]'
      views:
        | never
      pathParamNames:
        | 'atchAll'
    }
    'src/pages/admin/inquiries/index.vue': {
      routes:
        | '/admin/inquiries/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/inquiries/[id].vue': {
      routes:
        | '/admin/inquiries/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/jodalsa/index.vue': {
      routes:
        | '/jodalsa/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/jodalsa/[id].vue': {
      routes:
        | '/jodalsa/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/manual.vue': {
      routes:
        | '/manual'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/materials/index.vue': {
      routes:
        | '/materials/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/purchase/index.vue': {
      routes:
        | '/purchase/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/results/index.vue': {
      routes:
        | '/results/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/results/[id].vue': {
      routes:
        | '/results/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/tests/index.vue': {
      routes:
        | '/tests/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/[username].vue': {
      routes:
        | '/users/[username]'
      views:
        | never
      pathParamNames:
        | 'username'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
